public class ExceptionHandlingExample {

    public static void main(String[] args) {

        int[] numbers = {1, 2, 3, 4, 5};
        int divisor = 0;

        try {
            int result = numbers[5] / divisor;
            System.out.println("Result: " + result);
        } catch (ArithmeticException | ArrayIndexOutOfBoundsException | NullPointerException ex) {
            System.out.println("An exception occurred: " + ex);
        }
    }
}
